Adding custom categorical plotting of reef polygons to plot_map().
gbrrestoration/canonical-reefs pull request #10
Opened 2024-05-14 05:43 UTC by BG-AIMS

2024-05-15 07:55 UTC, ConnectedSystems commented on src/common.jl
> +    )
That double assignment isn't necessary I don't think:

```suggestion
    ga = GeoAxis(
        f[1, 1];
        dest="+proj=latlong +datum=WGS84",
        xlabel="Longitude",
        ylabel="Latitude",
        xticklabelpad=15,
        yticklabelpad=40,
        xticklabelsize=10,
        yticklabelsize=10,
        aspect=AxisAspect(0.75),
        xgridwidth=0.5,
        ygridwidth=0.5,
    )
```

2024-05-15 07:57 UTC, ConnectedSystems commented on src/common.jl
> +        tellheight=true, tellwidth=false, orientation=:horizontal, labelsize=10)
Is the `collect` necessary? I would have expected the iterables to work...

2024-05-15 07:57 UTC, ConnectedSystems requested changes
Looks fine to me, just two things to address

2024-05-26 12:20 UTC, ConnectedSystems commented on src/common.jl
> +    ColorSchemes
Good that you grouped like imports, but Blue style also says to alphabetize them too

2024-05-26 12:22 UTC, ConnectedSystems approved these changes
I'm okay merging this in after addressing one minor comment. Useful as a convenience function, thank you.

2024-05-28 06:39 UTC, BG-AIMS commented
Rebased branch onto main

2024-05-28 06:40 UTC, merged